local player_state_categories = {

    ledge_hanging = "mloc_disabled_player_state",
	warp_grabbed = "mloc_disabled_player_state",
	dead = "mloc_disabled_player_state",
	hogtied = "mloc_disabled_player_state",
	grabbed = "mloc_disabled_player_state",
	catapulted = "mloc_disabled_player_state",
	knocked_down = "mloc_disabled_player_state",
	consumed = "mloc_disabled_player_state",
	netted = "mloc_disabled_player_state",
	mutant_charged = "mloc_disabled_player_state",
	pounced = "mloc_disabled_player_state",
    stunned = "mloc_disabled_player_state",
    exploding = "mloc_disabled_player_state",
    ledge_hanging_falling = "mloc_disabled_player_state",
	ladder_top_leaving = "mloc_movement_player_state",
	ladder_top_entering = "mloc_movement_player_state",
	sliding = "mloc_movement_player_state",
	sprinting = "mloc_movement_player_state",
	jumping = "mloc_movement_player_state",
	lunging = "mloc_movement_player_state",
	ladder_climbing = "mloc_movement_player_state",
	dodging = "mloc_movement_player_state",
	walking = "mloc_movement_player_state",
	ledge_vaulting = "mloc_movement_player_state",
	falling = "mloc_movement_player_state",
	ledge_hanging_pull_up = "mloc_movement_player_state",  
}

return player_state_categories